fastlane_require 'dotenv'

PACKAGE_NAME = "com.shafayat.helloworld"
FIREBASE_APP_ID = "1:223943864343:android:eca85a1e4233bb2fd36c52"
KEYSTORE_PATH = nil
FIREBASE_KEY_PATH = nil
PLAYSTORE_KEY_PATH = nil
BUNDLE_FILE_PATH = nil
UPDATE_VERSION_CODE = nil

before_all do
  Dotenv.overload('.env.secret')
  KEYSTORE_PATH = Dir.pwd + "/../certificates/keystore.jks"
  FIREBASE_KEY_PATH = Dir.pwd + "/../certificates/firebase-app-distribution-key.json"
  PLAYSTORE_KEY_PATH = Dir.pwd + "/../certificates/playstore-app-distribution-key.json"
  BUNDLE_FILE_PATH = Dir.pwd + "/../app/build/outputs/bundle/release/app-prod-release.aab"
  puts ENV['KEYSTORE_PASSWORD']

end

# Run Unit test
desc "Run unit test"
lane :run_unit_test do
  gradle(
    task: "test"
  )
end


# Increase version code
lane :increment_version_code_in_project_gradle do
    version_code_from_play_store_strings = google_play_track_version_codes(
        package_name: PACKAGE_NAME,
        track: "alpha",
        json_key: PLAYSTORE_KEY_PATH
    )
    version_code_from_play_store = version_code_from_play_store_strings[0].to_i
    UPDATE_VERSION_CODE = version_code_from_play_store + 1
    increment_version_code(
        gradle_file_path: Dir.pwd + "/../app/build.gradle",
        version_code: UPDATE_VERSION_CODE.to_i
    )
end

# Assemble and build bundle file
lane :build do
    gradle(
        task: "bundle",
        build_type: "Release",
        properties: {
            "android.injected.signing.store.file" => KEYSTORE_PATH,
            "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
            "android.injected.signing.key.alias" => ENV['KEYSTORE_ALIAS'],
            "android.injected.signing.key.password" => ENV['KEYSTORE_PASSWORD']
        },
    )
end

# Distribute to firebase app distribution
lane :distribute_to_firebase do
    firebase_app_distribution(
        app: FIREBASE_APP_ID,
        release_notes: "Uploaded from CI/CD",
        android_artifact_path: BUNDLE_FILE_PATH,
        android_artifact_type: "AAB",
        service_credentials_file: FIREBASE_KEY_PATH
    )
end
# Distribute to play console
# Push updated code to github with release tag




